### ISSUE TITLE
（希望納期 4/23→4/18昼取り下げ）issueのレビュー手順

### ISSUE THREAD

**Issue by MasaoYOMODA** [waic/board#1]
幹事会MLの皆様
**https://github.com/waic/board/blob/master/README.md の中に記載したissueのレビュー手順自体をレビューいただきたくよろしくお願いします。**
**希望納期：4/23(火)**
賛成：(+1):+1:, 反対：(-1):-1:, 保留：(confised):confused:のいずれかをReactionください。
反対：(-1):-1:の場合、コメント追記もお願いします。

**Comment by MasaoYOMODA** [comment]
追記
Issueを使ったレビュー手順を提案していますが、
GitHubのチームディスカッション機能を使っても良いかもしれません。
こちらの機能を使ったほうが良い、という方は（confused）:confused:を投票し
「GitHubのチームディスカッション機能を使うほうが良さそう」とコメントしてください。
併せてよろしくお願いします。
https://dev.classmethod.jp/tool/github/github-team-discussion/

**Comment by bakera** [comment]
特に問題はないと思いますが、ブランチの運用は多分しないので、PRとブランチに関する記述は消しておいてもいいかもです。

**Comment by kentarou-fukuda** [comment]
1票でも反対があるとcloseになる（全会一致を原則）とするのは若干抵抗があります。
https://waic.jp/committee/rules/　だと大体過半数、厳しいもので2/3の様なので、手順上は過半数か2/3としておいて、運用上はなるべく全会一致を目指す方針とするのがいいのではないでしょうか？

**Comment by MasaoYOMODA** [comment]
@bakera @kentarou-fukuda コメントありがとうございました。
他皆様（、既に (+1):+1:された方も )
お二人のコメントに適宜 Reaction :+1: :-1: :confused: や追加コメントいただけると助かります。
引き続き 4/23（もしくは 幹事の皆様が1度以上Reactionする）までよろしくお願いします。

**Comment by MasaoYOMODA** [comment]
> 1票でも反対があるとcloseになる（全会一致を原則）とするのは若干抵抗があります。
> [https://waic.jp/committee/rules/　](https://waic.jp/committee/rules/%E3%80%80)
> だと大体過半数、厳しいもので2/3の様なので、手順上は過半数か2/3としておいて、運用上はなるべく全会一致を目指す方針とするのがいいのではないでしょうか？

作業部会や総会でのレビューではそうかもしれません。幹事会でのレビューでもそれでよいでしょうか？...と思ったのでconfused:confused:でReactionしました。 @kentarou-fukuda  福田さん、他皆様、いかがでしょう？

**Comment by MasaoYOMODA** [comment]
> 特に問題はないと思いますが、ブランチの運用は多分しないので、PRとブランチに関する記述は消しておいてもいいかもです。

リソースが増えた時のために（例えば 規程の細則相当を文書化し PRで修正提案を受け付ける、というような運用のために）記述は消さなくてもよいでしょうか？ @bakera 太田さん、他皆様、いかがでしょうか？

**Comment by kentarou-fukuda** [comment]
この件でもそうなのですが、私が「うーん」と思って-1すると止まってしまうのですよね。そうすると、本音は反対でも反対票を入れづらい状況が発生します。

また、幹事会内で何らかの意見の相違が生じた場合は、機能不全に陥ることも考えられるので、多数決で先に進める道は残したほうが良いのかな、と。

もう1点、メール等での承認/決議よりも条件が厳しいならissueおこさず承認/決議取れば良いわけで、簡便／迅速に運用するためのルールとしては本末転倒な気もします。

ということで、-1を入れておきます。

**Comment by MasaoYOMODA** [comment]
> この件でもそうなのですが、
（中略）
> ということで、-1を入れておきます。
なるほど。福田さんのコメントへの Reactionを confused:confused:から +1:+1:に変更します。

ということで福田さん、皆様、
4/18(木) 昼に このレビューを取り下げ、
・手順上は過半数か2/3としておいて、運用上はなるべく全会一致を目指す
ように Redame.md を書き換えて、
別issueで改めて 4/19(金)からレビュー依頼させてください。

**Comment by kentarou-fukuda** [comment]
@MasaoYOMODA さん、
ありがとうございます。お手数をおかけしますが、よろしくお願いいたします :bow:

**Comment by MasaoYOMODA** [comment]
いったん取り下げ、福田さん/太田さん 指摘を反映して改めてissue出します。よろしくお願いします。

**Comment by MasaoYOMODA** [comment]
>福田さん/太田さん 指摘を反映して改めてissue出します。

今日中を希望納期として https://github.com/waic/board/issues/2 を出しています。
@makojo @cocktailz Reaction 👍 ありがとうございました。
@MakotoUeki @kentarou-fukuda @bakera @SawadaStdDesign @DaichiImai 
恐縮ですが、引き続き #2 へのReactionお待ちしております。よろしくお願いします。m(_ _)m
