### ISSUE TITLE
（希望納期 4/23→4/27に延期）waic/boardにおけるissueのレビュー手順

### ISSUE THREAD

**Issue by MasaoYOMODA** [waic/board#2]
幹事会MLの皆様
福田さん/太田さん 指摘を https://github.com/waic/board/blob/master/README.md に反映しましたので、waic/boardにおけるissueのレビュー手順自体を改めてレビューいただきたくよろしくお願いします。
**希望納期：4/23(火)
賛成：(+1)👍, 反対：(-1)👎, 保留：(confised)😕のいずれかをReactionください。
反対：(-1)👎の場合、コメント追記もお願いします。**

**Comment by kentarou-fukuda** [comment]
確認遅くなり申し訳ありません。editorial なコメントですが、幹事会とboradメンバーの２つが使われているので幹事会メンバーに統一するのがいいかと思います。

よろしくお願いします。

**Comment by MasaoYOMODA** [comment]
@kentarou-fukuda Reaction とコメントありがとうございました。
皆様、Reame.md中の 「boradメンバー」を「幹事会メンバー」に修正した上で、このissueを（取り下げでなく）4/27(土)納期に延期します。皆様、不都合あればご指摘ください。
@SawadaStdDesign @bakera #1 で Reaction :+1: いただいておりますが、本isssue #2 にもReactionいただけると助かります。よろしくお願いします。
@MakotoUeki @kiyochika @DaichiImai 本isssue #2 にReaction ( :+1: :-1: :confused: ) いただけると助かります。よろしくお願いします。

**Comment by kiyochika** [comment]
@MasaoYOMODA 
本件自体は進めていただきたいので「賛成」としました。ですので、このコメントは今後の参考までに、ということなのですが、将来的にはissueを立てた上でかつMLに投稿する、というのは避けられるようにしたいです。おそらくはTeamを作成すれば可能ですよね、ということで。
よろしくお願いいたします。

**Comment by MasaoYOMODA** [comment]
@kiyochika 
>将来的にはissueを立てた上でかつMLに投稿する、というのは避けられるようにしたいです。おそらくはTeamを作成すれば可能ですよね
の主旨は了解しました。後日、本issueとは別のissueとして確認させてください。よろしくお願いします。

**Comment by MasaoYOMODA** [comment]
遅くなりましたが 6名の皆様より＋1 👍 のReactionいただきましたので
>賛成が幹事会メンバーの2/3を超えた場合 issueは承認されたものとして（ issueにその旨記載した上で）Closeする。
とさせていただきます。よろしくお願いします。
